#!/bin/bash
# Sets up a temporary subscriber test account for Playwright CI on andrewbaker.ninja.
#
# The plugin's Test Account Manager creates a subscriber-level account with an
# application password. Subscriber accounts are NOT subject to admin 2FA forcing,
# so they work for automated tests without ever touching 2FA settings.
#
# Usage:
#   bash setup-playwright-test-account.sh               # 30-min TTL
#   bash setup-playwright-test-account.sh --ttl 3600    # 1-hour TTL
#
# Writes credentials to .env.test (gitignored) for use in Playwright tests.
#
# IMPORTANT: These are subscriber accounts — they cannot access wp-admin pages.
# For admin UI tests that require interactive 2FA, a human must run the test
# and enter the 2FA code manually.
#
# DO NOT modify 2FA settings to work around this. The correct approach is this script.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_CREATE="${SCRIPT_DIR}/../create-test-account.sh"

if [ ! -f "${SHARED_CREATE}" ]; then
    echo "ERROR: shared create-test-account.sh not found at ${SHARED_CREATE}"
    echo "       Expected at: $(realpath "${SHARED_CREATE}" 2>/dev/null || echo "${SHARED_CREATE}")"
    exit 1
fi

TTL_ARGS=("$@")

echo "Creating Playwright test account (subscriber + app password)..."
OUTPUT=$(bash "${SHARED_CREATE}" "${TTL_ARGS[@]}")
echo "${OUTPUT}"

# Extract JSON block
JSON=$(echo "${OUTPUT}" | awk '/^\{/,/^\}/')

if [ -z "${JSON}" ]; then
    echo "ERROR: Could not parse credentials from output."
    exit 1
fi

USERNAME=$(echo "${JSON}" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['username'])" 2>/dev/null)
APP_PW=$(echo "${JSON}"   | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['app_password'])" 2>/dev/null)
EXPIRES=$(echo "${JSON}"  | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['expires_human'])" 2>/dev/null)

if [ -z "${USERNAME}" ] || [ -z "${APP_PW}" ]; then
    echo "ERROR: Could not extract username/app_password from JSON."
    exit 1
fi

ENV_FILE="${SCRIPT_DIR}/.env.test"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup-playwright-test-account.sh — do not commit
# Expires: ${EXPIRES}
# Role: subscriber (no admin access — use WP-CLI for server-side checks)
WP_TEST_USER=${USERNAME}
WP_TEST_APP_PASS=${APP_PW}
WP_SITE=https://andrewbaker.ninja
EOF

echo ""
echo "Written to .env.test:"
echo "  WP_TEST_USER=${USERNAME}"
echo "  Expires: ${EXPIRES}"
echo ""
echo "Load in Playwright: require('dotenv').config({ path: '.env.test' })"
